name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup GCC
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest

      - name: Setup GoogleTest
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0

      - name: Run tests
        run: make test
